---
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: incl.yml
    - name: list installed apache2
      raw: apt list --installed|grep apache2>>/tmp/1.log
