---
- hosts: all
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - name: user creation
      user:
              name: "{{ item }}"
              state: present
      with_items:
            - user2
            - user3

