---
- hosts: all
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - name : indexing loop
      debug:
              msg: "echo hello ansible {{ item.0 }} and {{ item.1 }}"
      with_indexed_items:
              - "hello"
              - "hi"
